kind = "web"
previewPath = "/"
title = "Casei de Lafer"
version = "1.0.0"
id = "artifacts/casei-de-lafer"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23059

[services.development]
run = "pnpm --filter @workspace/casei-de-lafer run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/casei-de-lafer", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/casei-de-lafer", "run", "start" ]

[services.env]
PORT = "23059"
